# Generated by Django 3.0 on 2019-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('time_to_reach_dest', models.DateTimeField()),
                ('email', models.EmailField(max_length=100)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('ride_time', models.IntegerField()),
                ('state', models.IntegerField(default=0)),
                ('pending_time', models.IntegerField(default=0)),
                ('frequency', models.SmallIntegerField(default=0)),
                ('traffic_time', models.IntegerField()),
            ],
            options={
                'db_table': 'scheduled_trip',
            },
        ),
    ]
